name: Cockpit Enclave Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
              
    - name: Setup Node (SDK)
      uses: actions/setup-node@v2

    - name: Install Node Modules
      run: npm i

    - name: Run Make
      run: make 

    - name: Webpack Build
      run: npx webpack

    - name: Create Tarbakll
      run: |
      mkdir cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}
      cp dist cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}
      tar --create --file cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}.tar.gz cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}

    - name: build RPM package
      run: |
        apt install -y rpmdevtools rpmlint
        rpmdev-setuptree
        cp build/cockpit-enclave.spec ~/rpmbuild/SPECS
        cp cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}.tar.gz ~/rpmbuild/SOURCES
        rpmbuild --define="version ${{ steps.gitversion.outputs.SemVer }}"
        rpmbuild -bb ~/rpmbuild/SPECS/cockpit-enclave.spec
      

    - name: Archive build packages
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}.tar.gz
          ~/rpmbuild/RPMS/noarch/*.rpm

    - name: Create Release    
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.gitversion.outputs.SemVer }}
        release_name: Release v${{ steps.gitversion.outputs.SemVer }}
        body: Latest SDK API Release

    - name: Upload Release Asset        
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}.tar.gz
        asset_name: cockpit-enclave-v${{ steps.gitversion.outputs.SemVer }}.tar.gz
        asset_content_type: application/x-tar