name: Cockpit Enclave Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
              
    - name: Setup Node (SDK)
      uses: actions/setup-node@v2

    - name: Install Node Modules
      run: npm i

    - name: Get patternfly library
      run: |
        git fetch --depth=1 https://github.com/cockpit-project/cockpit.git 253; \
        git checkout --force FETCH_HEAD -- pkg/lib; \
        git reset -- pkg/lib; \
        mv pkg/lib src/ && rmdir -p pkg 

    - name: Webpack Build
      run: npx webpack

    - name: build RPM package
      run: |
        mkdir cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}
        cp -r dist/. cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}
        tar --create --file cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}
        mkdir -p ~/rpmbuild/BUILD ~/rpmbuild/BUILDROOT ~/rpmbuild/RPMS ~/rpmbuild/SOURCES ~/rpmbuild/SPECS ~/rpmbuild/SRPMS
        cp build/rpm/cockpit-enclave.spec ~/rpmbuild/SPECS
        cp cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz ~/rpmbuild/SOURCES
        rpmbuild -bb --define="version ${{ steps.gitversion.outputs.AssemblySemVer }}" ~/rpmbuild/SPECS/cockpit-enclave.spec
        cp -r ~/rpmbuild/RPMS/noarch/cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}-1.noarch.rpm ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.noarch.rpm

    - name: Build DEB Package
      run: |
        mkdir -p build/deb/usr/share/cockpit/enclave
        cp -r dist/. build/deb/usr/share/cockpit/enclave
        sed -i 's/{{version}}/${{ steps.gitversion.outputs.AssemblySemVer }}/g' ./build/deb/debian/control
        dpkg -b ./build/deb ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.deb

    - name: Archive build packages
      uses: actions/upload-artifact@v2
      with:
        name: cockpit-enclave-files
        path: |
          ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.noarch.rpm
          ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.deb

    # - name: Create Release 
    #   id: create_release   
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: v${{ steps.gitversion.outputs.AssemblySemVer }}
    #     release_name: Release v${{ steps.gitversion.outputs.AssemblySemVer }}
    #     body: Latest SDK API Release

    # - name: Upload RPM Release Asset        
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.noarch.rpm
    #     asset_name: cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.noarch.rpm
    #     asset_content_type: application/octet-stream

    # - name: Upload Deb Release Asset        
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.deb
    #     asset_name: cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.deb
    #     asset_content_type: application/octet-stream