name: Cockpit Enclave Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
              
    - name: Setup Node (SDK)
      uses: actions/setup-node@v2

    - name: Install Node Modules
      run: npm i

    - name: Run Make
      run: make 

    - name: Webpack Build
      run: npx webpack

    - name: Create Tarbakll
      run: |
        mkdir cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}
        cp -r dist/. cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}
        tar --create --file cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}

    - name: build RPM package
      run: |
        mkdir -p ~/rpmbuild/BUILD ~/rpmbuild/BUILDROOT ~/rpmbuild/RPMS ~/rpmbuild/SOURCES ~/rpmbuild/SPECS ~/rpmbuild/SRPMS
        cp build/cockpit-enclave.spec ~/rpmbuild/SPECS
        cp cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz ~/rpmbuild/SOURCES
        rpmbuild -bb --define="version ${{ steps.gitversion.outputs.AssemblySemVer }}" ~/rpmbuild/SPECS/cockpit-enclave.spec      

    - name: Archive build packages
      uses: actions/upload-artifact@v2
      with:
        name: cockpit-enclave-files
        path: |
          cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz
          ~/rpmbuild/RPMS/noarch/*.rpm

    - name: Create Release    
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.gitversion.outputs.AssemblySemVer }}
        release_name: Release v${{ steps.gitversion.outputs.AssemblySemVer }}
        body: Latest SDK API Release

    - name: Upload Release Asset        
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz
        asset_name: cockpit-enclave-${{ steps.gitversion.outputs.AssemblySemVer }}.tar.gz
        asset_content_type: application/x-tar